### ISSUE TITLE
Python 3.12

### ISSUE THREAD

**Issue by sbrunner** [vacanza/lingva#11]
Here https://github.com/vacanza/lingva/blob/main/src/lingva/extract.py#L187
`readfp` is used, but it didn't exist anymore in Python 3.12, `read_file` should be used
See: https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read_file

**Comment by arkid15r** [comment]
Thanks for reporting this!

**Comment by sbrunner** [comment]
Thanks :-)
